Update babel-eslint 5.0.0-beta6 -> 5.0.0-beta10
The current version gives me the following error when I try to run tests
on master:

> TypeError: Cannot read property 'visitClass' of undefined

It looks like this has since been resolved by the related packages, so
we can avoid this problem by bumping versions.

More info: https://github.com/babel/babel-eslint/issues/243